version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "8000:8000"
    networks:
      - back
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "8001:8001"
    networks: 
     - back
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: omar
      MONGODB_INITDB_ROOT_PASSWORD: admin
    
    networks: 
     - back

networks:
  back:

volumes: 
  mongodb_data:
